title: minwoo-kang.com
email: null
description: Minwoo Kang's Blog
url: https://minwoo-kang.com
keywords:
  - blog
timezone: Asia/Seoul
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: '/articles/:year-:month/:title'
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
owner:
  name: Minwoo
  avatar: ''
  job: ''
  bio: Software Engineer @ Naver
  email: null
  disqus-shortname: null
  google:
    analytics: null
    verify: null
    ad-client: null
    ad-slot: null
  github: mwkang
  linkedin: mwkang
